---
title: "Hedonic Home Price Prediction"
author: "Jonathon Sun, Johnathan Clementi"
date: "9/29/2021"
output: html_document
---

```{r setup, include=FALSE}
pacman::p_load(tidyverse, tidycensus, sf, kableExtra, tmap, viridis, esquisse, gridExtra, spdep, caret, ckanr, FNN, grid, gridExtra, ggcorplot, rgdal)

# rm(list=ls()) ##Clear my objects from memory

#Avoid getting results in scientific notation!
options(scipen = 999)

source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")

palette5 <- c("#25CB10", "#5AB60C", "#8FA108",   "#C48C04", "#FA7800")


```

## Pulling Data

```{r tidycensus pressure, echo=FALSE}

#variables on frequency of Race
Variables <- load_variables(2019,
                            "acs5",
                            cache = TRUE) %>%
  mutate(Merge_name = paste(name,"E", sep ="")) %>%
  filter(grepl("RACE", concept)) %>%
  filter(!grepl("AGE", concept)) %>%
  slice(1:10)

#variable median age, men and women not by race
A <- load_variables(2019,
                    "acs5",
                    cache = TRUE) %>%
  mutate(Merge_name = paste(name,"E", sep ="")) %>%
  filter(grepl("MEDIAN", concept)) %>%
  slice(1:3)

#Median Household Income
B <- load_variables(2019,
                    "acs5",
                    cache = TRUE) %>%
  mutate(Merge_name = paste(name,"E", sep ="")) %>%
  filter(grepl("MEDIAN INCOME", concept)) %>%
  slice(1)

# Cost of living
C <- load_variables(2019,
                    "acs5",
                    cache = TRUE) %>%
  mutate(Merge_name = paste(name,"E", sep ="")) %>%
  filter(grepl("COST", concept)) %>%
  slice(1:19)

Variables <- bind_rows(Variables, A, B, C)



# Pull census data using tidycensus

# Set CRS for project
CO_statePlaneCentral = "ESRI:102254"

# Read in census tracts
acsTractsCol.2019.sf <- get_acs(geography = "tract",
        year = 2019,
        variables = Variables$name, 
        state="Colorado",
        county= c("Boulder"),
        geometry=T,
        output = "wide") %>% 
  st_transform(CO_statePlaneCentral) %>%
  dplyr::select (GEOID, NAME, all_of(paste0(Variables$name,"E")))

ggplot() +
  geom_sf(data = acsTractsCol.2019.sf) +
  labs(title = "Census Tracts, Boulder County, Colorado")

# Read in census Block groups
acsBGCol.2019.sf <- get_acs(geography = "block group",
        year = 2019,
        variables = Variables$name, 
        state="Colorado",
        county= c("Boulder"),
        geometry=T,
        output = "wide") %>% 
  st_transform(CO_statePlaneCentral) %>%
  dplyr::select (GEOID, NAME, all_of(paste0(Variables$name,"E")))

ggplot() +
  geom_sf(data = acsBGCol.2019.sf)+
  labs(title = "Census Block Groups, Boulder County, Colorado")

```

Website available for data https://open-data.bouldercolorado.gov/ 


```{r colorado_data}

# Locations of Rental Properties (by license)
## https://open-data.bouldercolorado.gov/datasets/92f70ea894ef47a582bb0d656aa4aa7d_0/explore?location=40.013774%2C-105.256817%2C16.81
rentalHomes <- st_read("https://opendata.arcgis.com/datasets/92f70ea894ef47a582bb0d656aa4aa7d_0.geojson") %>%
  st_transform(CO_statePlaneCentral)

ggplot() +
  geom_sf(data = st_union(acsTractsCol.2019.sf),
          fill = "transparent") +
  geom_sf(data = st_centroid(rentalHomes)) +
  labs(title = "Rental Homes")


# Locations of Accessory Dwelling Units
## https://open-data.bouldercolorado.gov/datasets/669935e6d13c406497cd9cbbbd7951b2_0/explore?location=40.023716%2C-105.253583%2C11.91
## For explanation on what ADU's are: https://planning.org/knowledgebase/accessorydwellings/ 
adus <- st_read("https://opendata.arcgis.com/datasets/669935e6d13c406497cd9cbbbd7951b2_0.geojson") %>%
  st_transform(CO_statePlaneCentral)

ggplot() +
  geom_sf(data = st_union(acsTractsCol.2019.sf),
          fill = "transparent") +
  geom_sf(data = adus) +
  labs(title = "Accessory Dwelling Units")


# Locations of 100 Year floodplain within Boulder County
# Data originally for the whole state, subsetted to Boulder County via st_intersect
## https://geo.colorado.edu/catalog/47540-5ca228ffd43267000b8c7448
## About this dataset: https://open-data.bouldercolorado.gov/datasets/bfc343d63cf54831810b983b36ce6872_3/about


# # Process for creating Boulder County Flood Plains shp
# COState_flood <- st_read("CO_state_100yrFloodplains.geojson") %>%
#   st_transform(CO_statePlaneCentral)
# 
# boulderCo_flood <- COState_flood %>%
#   st_intersection(st_union(acsTractsCol.2019.sf)) %>%
#   st_sf()
# 
# # Create Geopackage for ease of transport - only one file
# st_write(boulderCo_flood, "boulderCo_100yrFloodZones.gpkg")

boulderCo_flood_shp <- st_read("boulderCo_100yrFloodZones.gpkg")


ggplot() +
  geom_sf(data = st_union(acsTractsCol.2019.sf),
          fill = "transparent") +
  geom_sf(data = boulderCo_flood_shp)


# Locations of Zoning districts
## https://open-data.bouldercolorado.gov/datasets/e88004e26b9e42cfba32129fb8731f41_0/explore?location=40.025701%2C-105.239775%2C11.45
## City of Boulder Colorado Zoning Districts. Including residential, business, industrial, public, agricultural, mix of residential and business, residential mobile homes, main street area and mixed density residential.
zoning <- st_read("https://opendata.arcgis.com/datasets/e88004e26b9e42cfba32129fb8731f41_0.geojson") %>%
  st_transform(CO_statePlaneCentral)

ggplot() +
  geom_sf(data = st_union(acsTractsCol.2019.sf),
          fill = "transparent") +
  geom_sf(data = zoning) +
  labs(title = "Zoning Districts")


# Locations of 19 libraries 
## https://opendata-bouldercounty.hub.arcgis.com/datasets/libraries-2/explore?location=40.001009%2C-105.302539%2C11.28

Col_Library <- st_read("https://opendata.arcgis.com/datasets/7f4ea25ba87345e380d2e896611d2588_0.geojson") %>%
  st_transform(CO_statePlaneCentral)

ggplot() +
  geom_sf(data = st_union(acsTractsCol.2019.sf),
          fill = "transparent") +
  geom_sf(data = Col_Library) +
  labs(title = "library")


#addresses for buildings https://open-data.bouldercolorado.gov/datasets/d63e537da54640bd967c2fedc4c99a92_0/explore?location=40.026211%2C-105.232810%2C11.82 
Addresses <- st_read("https://opendata.arcgis.com/datasets/d63e537da54640bd967c2fedc4c99a92_0.geojson") %>%
  st_transform(CO_statePlaneCentral)

ggplot() +
  geom_sf(data = st_union(acsTractsCol.2019.sf),
          fill = "transparent") +
  geom_sf(data = Addresses) +
  labs(title = "Addresses")


# Properties managed by parks and recreation polygons ## https://open-data.bouldercolorado.gov/datasets/fdfc0410e75c48b6b9e53cf94bdbe224_1/explore?location=40.026750%2C-105.234200%2C12.05 
Parks <- st_read("https://opendata.arcgis.com/datasets/fdfc0410e75c48b6b9e53cf94bdbe224_1.geojson")


# Urban trees
## https://open-data.bouldercolorado.gov/datasets/dbbae8bdb0a44d17934243b88e85ef2b_0/explore?location=40.015538%2C-105.275671%2C16.12
trees <- st_read("https://opendata.arcgis.com/datasets/dbbae8bdb0a44d17934243b88e85ef2b_0.geojson") %>%
    st_transform(CO_statePlaneCentral)

ggplot() +
  geom_sf(data = st_union(acsTractsCol.2019.sf),
          fill = "transparent") +
  geom_sf(data = trees) +
  labs(title = "Street Trees")


# Grocery Stores from Data Axle
Grocery_Store <- read.csv("DataAxle_GroceryStores.csv") %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326, agr = "constant") %>%
  st_transform(CO_statePlaneCentral) 

ggplot() +
  geom_sf(data = st_union(acsTractsCol.2019.sf),
          fill = "transparent") +
  geom_sf(data = Grocery_Store) +
  labs(title = "Grocery_Stores")

#Restaurants from DataAxle
Restaurants <- bind_rows(read.csv("DataAxle_Restaurants_1.csv"), read.csv("DataAxle_Restaurants_2.csv")) %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326, agr = "constant") %>%
  st_transform(CO_statePlaneCentral)

ggplot() +
  geom_sf(data = st_union(acsTractsCol.2019.sf),
          fill = "transparent") +
  geom_sf(data = Restaurants) +
  labs(title = "Restaurants")


#Education from DataAxle
Education <- read.csv("DataAxle_Education.csv") %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326, agr = "constant") %>%
  st_transform(CO_statePlaneCentral)

ggplot() +
  geom_sf(data = st_union(acsTractsCol.2019.sf),
          fill = "transparent") +
  geom_sf(data = Education) +
  labs(title = "Schools")

#Museums from DataAxle
Museums <- read.csv("DataAxle_Musuems.csv") %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326, agr = "constant") %>%
  st_transform(CO_statePlaneCentral)

ggplot() +
  geom_sf(data = st_union(acsTractsCol.2019.sf),
          fill = "transparent") +
  geom_sf(data = Museums) +
  labs(title = "Museums")


```

```{r, trainingData}
studentData <- st_read("studentData.geojson", crs = CO_statePlaneCentral) 

summary(studentData)

ggplot() +
  geom_sf(data = st_union(acsTractsCol.2019.sf),
          fill = "transparent") +
  geom_sf(data = studentData) +
  labs(title = "Training Data")
```

# Exploratory analysis

Visualize price per sq foot
```{r}
BCC_houses <- studentData %>%
  mutate(pricePerSF = price/TotalFinishedSF,
         age = 2021 - builtYear,
         iprvmntAge = 2021 - EffectiveYear)

ggplot() +
  geom_sf(data = acsBGCol.2019.sf, fill = "grey40") +
  geom_sf(data = BCC_houses, aes(colour = q5(pricePerSF)), 
          show.legend = "point", size = .75) +
  scale_colour_manual(values = palette5,
                   labels=qBr(BCC_houses,"pricePerSF"),
                   name="Quintile\nBreaks") +
  labs(title="Price Per Square Foot, Boulder Ccounty Colorado") +
  mapTheme()
```

Visualize price as a function of various continuous variables
```{r}
st_drop_geometry(BCC_houses) %>% 
  dplyr::select(price, TotalFinishedSF, age, iprvmntAge) %>%
  filter(price <= 5000000, age < 500) %>%
  gather(Variable, Value, -price) %>% 
   ggplot(aes(Value, price)) +
     geom_point(size = .5) + geom_smooth(method = "lm", se=F, colour = "#FA7800") +
     facet_wrap(~Variable, ncol = 3, scales = "free") +
     labs(title = "Price as a function of continuous variables") +
     plotTheme()
```

Price as a function of categorical variables
```{r, fig.height=15, fig.width=10}
st_drop_geometry(BCC_houses) %>% 
  dplyr::select(price, designCodeDscr, ConstCodeDscr, carStorageTypeDscr) %>%
  # mutate(NUM_FLOORS = as.factor(NUM_FLOORS)) %>%
  filter(price <= 5000000) %>%
  gather(Variable, Value, -price) %>% 
   ggplot(aes(Value, price)) +
     geom_bar(position = "dodge", stat = "summary", fun.y = "mean") +
     facet_wrap(~Variable, ncol = 1, scales = "free") +
     labs(title = "Price as a function of\ncategorical variables", y = "Mean_Price") +
     plotTheme() + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

Correlation matrix
```{r}
numericVars <- 
  select_if(st_drop_geometry(BCC_houses), is.numeric) %>% filter(toPredict == 0) %>% na.omit()

ggcorrplot(
  round(cor(numericVars), 1), 
  p.mat = cor_pmat(numericVars),
  colors = c("#25CB10", "white", "#FA7800"),
  type="lower",
  insig = "blank") +  
    labs(title = "Correlation across numeric variables")
```

